// lib/eye-data.js — 안과 시술 데이터

export const EYE_META = {
  industry: "eye",
  label: "안과",
  minLength: 2000,
};

export const EYE_TREATMENTS = [
  // ─── 시력교정 ───
  {
    id: "lasik",
    industry: "eye",
    name: "라식",
    cat: "시력교정",
    emoji: "👁️",
    titlePatterns: [
      "{region} 안과 라식 후기｜수술 1일차부터 1개월까지 솔직 기록",
      "{region} 라식 vs 라섹 비교하다 결정한 이유",
      "{region} 안과 라식 처음 받아봤어요｜통증·회복 솔직 후기",
    ],
    keywords: ["라식", "라식수술", "{region}라식", "{region}안과라식", "라식후기"],
    compareWith: "라섹",
  },
  {
    id: "lasek",
    industry: "eye",
    name: "라섹",
    cat: "시력교정",
    emoji: "👀",
    titlePatterns: [
      "{region} 안과 라섹 후기｜통증 1일차부터 1개월까지 솔직 기록",
      "{region} 라섹 회복 기간 솔직 일지｜다운타임 직접 겪어본 후기",
      "{region} 안과 라섹 vs 라식 고민 끝에 결정한 이유",
    ],
    keywords: ["라섹", "라섹수술", "{region}라섹", "{region}안과라섹", "라섹회복", "라섹후기"],
    compareWith: "라식",
  },
  {
    id: "smile_lasik",
    industry: "eye",
    name: "스마일라식",
    cat: "시력교정",
    emoji: "😊",
    titlePatterns: [
      "{region} 안과 스마일라식 후기｜절개 작은 수술 1개월 기록",
      "{region} 스마일라식 vs 라식 비교한 이야기",
    ],
    keywords: ["스마일라식", "스마일라식후기", "{region}스마일라식", "{region}안과스마일라식"],
    compareWith: "라식",
  },
  {
    id: "icl",
    industry: "eye",
    name: "안내렌즈삽입술",
    cat: "시력교정",
    emoji: "💎",
    titlePatterns: [
      "{region} 안과 ICL 안내렌즈삽입술 후기｜고도근시 솔직 기록",
      "{region} ICL vs 라식 비교 끝에 결정한 이유",
    ],
    keywords: ["ICL", "안내렌즈삽입술", "고도근시수술", "{region}ICL", "{region}안과ICL"],
    compareWith: "라식",
  },
  {
    id: "rle",
    industry: "eye",
    name: "렌즈교환술(RLE)",
    cat: "시력교정",
    emoji: "🔮",
    titlePatterns: [
      "{region} 안과 렌즈교환술 후기｜노안·고도근시 동시 교정 기록",
      "{region} RLE vs 라식 비교한 솔직 후기",
      "{region} 렌즈교환술 1개월 일지",
    ],
    keywords: ["렌즈교환술", "RLE", "다초점인공수정체", "노안교정수술", "{region}렌즈교환술"],
    compareWith: "라식",
  },

  // ─── 백내장·노안 ───
  {
    id: "cataract",
    industry: "eye",
    name: "백내장 수술",
    cat: "백내장·노안",
    emoji: "🔍",
    titlePatterns: [
      "{region} 안과 백내장 수술 후기｜다초점렌즈 선택한 이유 솔직 정리",
      "{region} 백내장 수술 1개월 일지｜시야가 다시 밝아진 기록",
      "{region} 안과 백내장 vs 노안 교정 고민한 이야기",
    ],
    keywords: ["백내장", "백내장수술", "다초점렌즈", "{region}백내장", "{region}안과백내장"],
    compareWith: "단초점렌즈",
  },
  {
    id: "presbyopia",
    industry: "eye",
    name: "노안 교정",
    cat: "백내장·노안",
    emoji: "📖",
    titlePatterns: [
      "{region} 안과 노안 교정 후기｜다초점 렌즈 선택한 이유 솔직 정리",
      "{region} 노안 교정 1개월 일지｜돋보기 벗고 달라진 일상",
      "{region} 안과 노안 교정 vs 돋보기 비교 끝에 결정한 이유",
    ],
    keywords: ["노안교정", "노안수술", "다초점렌즈", "{region}노안교정", "{region}안과노안교정"],
    compareWith: "돋보기",
  },

  // ─── 망막·녹내장 ───
  {
    id: "retina",
    industry: "eye",
    name: "망막 질환",
    cat: "망막·녹내장",
    emoji: "🩺",
    titlePatterns: [
      "{region} 안과 망막 검진 후기｜비문증 시작되고 받아본 정밀검사",
      "{region} 망막 정밀검진 후기｜안저·OCT 결과 솔직 정리",
      "{region} 안과 망막 질환 진단받고 한 것들",
    ],
    keywords: ["망막검진", "망막질환", "안저검사", "OCT검사", "망막박리", "{region}망막"],
    compareWith: "경과 관찰",
  },
  {
    id: "glaucoma",
    industry: "eye",
    name: "녹내장",
    cat: "망막·녹내장",
    emoji: "💧",
    titlePatterns: [
      "{region} 녹내장 진단 후기｜안압 관리 기록",
      "{region} 안과 녹내장 처음 진단받은 날",
    ],
    keywords: ["녹내장", "안압검사", "녹내장치료", "{region}녹내장"],
    compareWith: "경과 관찰",
  },
  {
    id: "macular",
    industry: "eye",
    name: "황반변성",
    cat: "망막·녹내장",
    emoji: "🎯",
    titlePatterns: [
      "{region} 황반변성 주사치료 후기",
      "{region} 안과 황반변성 진단 솔직 후기",
    ],
    keywords: ["황반변성", "안구주사", "{region}황반변성"],
    compareWith: "경과 관찰",
  },
  {
    id: "diabetic_retina",
    industry: "eye",
    name: "당뇨망막병증",
    cat: "망막·녹내장",
    emoji: "🩸",
    titlePatterns: [
      "{region} 당뇨망막병증 검진 후기",
      "{region} 안과 당뇨 합병증 관리한 이야기",
    ],
    keywords: ["당뇨망막병증", "당뇨안과", "{region}당뇨망막"],
    compareWith: "경과 관찰",
  },
  {
    id: "floaters",
    industry: "eye",
    name: "비문증",
    cat: "망막·녹내장",
    emoji: "👁‍🗨",
    titlePatterns: [
      "{region} 비문증 안과 검진 후기｜시야 점이 보이기 시작했을 때",
      "{region} 안과 비문증 정밀검사 받아본 솔직 후기",
      "{region} 비문증 원인·검사 솔직 정리",
    ],
    keywords: ["비문증", "비문증치료", "비문증검사", "날파리증", "{region}비문증", "{region}안과비문증"],
    compareWith: "경과 관찰",
  },

  // ─── 안구건조·결막 ───
  {
    id: "dry_eye",
    industry: "eye",
    name: "안구건조증",
    cat: "안구건조·결막",
    emoji: "💦",
    titlePatterns: [
      "{region} 안구건조증 IPL 치료 후기",
      "{region} 안과 안구건조 원인 찾은 이야기",
    ],
    keywords: ["안구건조증", "IPL안구건조", "마이봄샘", "{region}안구건조"],
    compareWith: "인공눈물",
  },
  {
    id: "conjunctivitis",
    industry: "eye",
    name: "결막염",
    cat: "안구건조·결막",
    emoji: "👁️‍🗨️",
    titlePatterns: [
      "{region} 안과 결막염 치료 후기",
      "{region} 알레르기성 결막염 해결한 이야기",
    ],
    keywords: ["결막염", "알레르기결막염", "유행성결막염", "{region}결막염"],
    compareWith: "안약",
  },
  {
    id: "stye",
    industry: "eye",
    name: "다래끼·눈꺼풀염",
    cat: "안구건조·결막",
    emoji: "👁",
    titlePatterns: [
      "{region} 다래끼 절개 후기｜병원 안 가고 버티다가",
      "{region} 안과 눈꺼풀염 치료 솔직 후기",
    ],
    keywords: ["다래끼", "다래끼절개", "눈꺼풀염", "{region}다래끼"],
    compareWith: "온찜질",
  },
  {
    id: "pterygium",
    industry: "eye",
    name: "익상편 수술",
    cat: "안구건조·결막",
    emoji: "🌀",
    titlePatterns: [
      "{region} 익상편 수술 후기｜군날개 제거 1개월 기록",
      "{region} 안과 익상편 진단받고 결정한 이유",
      "{region} 군날개 수술 vs 경과 관찰 고민한 이야기",
    ],
    keywords: ["익상편", "익상편수술", "군날개", "군날개수술", "{region}익상편"],
    compareWith: "경과 관찰",
  },

  // ─── 사시·소아안과 ───
  {
    id: "strabismus",
    industry: "eye",
    name: "사시 교정",
    cat: "사시·소아안과",
    emoji: "👶",
    titlePatterns: [
      "{region} 사시 수술 후기｜아이 교정 기록",
      "{region} 안과 사시 진단 받고 결정한 이야기",
    ],
    keywords: ["사시교정", "사시수술", "소아사시", "{region}사시"],
    compareWith: "안경교정",
  },
  {
    id: "myopia_control",
    industry: "eye",
    name: "근시 진행 억제",
    cat: "사시·소아안과",
    emoji: "👓",
    titlePatterns: [
      "{region} 안과 아이 근시 진행 억제 후기",
      "{region} 드림렌즈 vs 아트로핀 고민한 이야기",
    ],
    keywords: ["근시억제", "드림렌즈", "아트로핀", "{region}소아안과"],
    compareWith: "일반안경",
  },
  {
    id: "dream_lens",
    industry: "eye",
    name: "드림렌즈",
    cat: "사시·소아안과",
    emoji: "🌙",
    titlePatterns: [
      "{region} 드림렌즈 후기｜아이 근시 진행 1년 일지",
      "{region} 안과 드림렌즈 처음 착용한 날 기록",
      "{region} 드림렌즈 vs 아트로핀 비교하다 결정한 이유",
    ],
    keywords: ["드림렌즈", "드림렌즈후기", "각막굴절교정렌즈", "OK렌즈", "{region}드림렌즈", "{region}안과드림렌즈"],
    compareWith: "아트로핀",
  },
  {
    id: "amblyopia",
    industry: "eye",
    name: "약시 치료",
    cat: "사시·소아안과",
    emoji: "🧒",
    titlePatterns: [
      "{region} 약시 치료 후기｜아이 교정 일지",
      "{region} 안과 약시 진단받고 한 것들",
    ],
    keywords: ["약시치료", "소아약시", "가림치료", "{region}약시"],
    compareWith: "경과 관찰",
  },

  // ─── 검진·상담 ───
  {
    id: "eye_checkup",
    industry: "eye",
    name: "안과 정밀검진",
    cat: "검진·상담",
    emoji: "🔬",
    titlePatterns: [
      "{region} 안과 정밀검진 후기",
      "{region} 시력검사·안저검사 받아봤어요",
    ],
    keywords: ["안과검진", "안저검사", "시력검사", "{region}안과"],
    compareWith: "",
  },
  {
    id: "contact_lens",
    industry: "eye",
    name: "콘택트렌즈 처방",
    cat: "검진·상담",
    emoji: "🟢",
    titlePatterns: [
      "{region} 안과 콘택트렌즈 처방 후기｜처음 착용 솔직 기록",
      "{region} 하드렌즈 vs 소프트렌즈 비교 끝에 결정한 이유",
      "{region} 콘택트렌즈 검사 받아본 후기",
    ],
    keywords: ["콘택트렌즈", "하드렌즈", "소프트렌즈", "렌즈처방", "{region}안과렌즈"],
    compareWith: "안경",
  },
];
