// ============================================================
// lib/neuro-data.js — 신경외과 시술 데이터 v3 (pain v3 기반)
// 핵심 분리: 환자 사고 흐름 = "검사(MRI/CT) 기반 + 신경 압박/저림/수술 고민"
// pain과 치료명 겹침 → industry='neuro' + id에 neuro_ 접두사로 구분
// ============================================================

export const NEURO_META = {
  industry: "neuro",
  label: "신경외과",
  greeting: "안녕하세요! 신경외과 블로그 글 도와드릴게요.",
  examples: [
    "강남 허리디스크 후기",
    "분당 신경차단술 후기",
    "수원 만성두통 신경외과 후기",
    "인천 수근관증후군 후기",
  ],
  badge: "🧠 신경외과",
  minLength: 2000,
};

export const NEURO_CATS = [
  "전체",
  "척추·디스크",
  "두통·신경통",
  "신경차단·통증",
  "말초신경·손저림",
  "어지럼·뇌신경",
];

export const NEURO_TREATMENTS = [
  // ─── 척추·디스크 ─── (pain과 분리: neuro = MRI/신경압박/수술고민)
  {
    id: "neuro_disc",
    industry: "neuro",
    name: "허리디스크",
    cat: "척추·디스크",
    emoji: "🦴",
    titlePatterns: [
      "{region} 허리디스크 신경외과 후기｜MRI 후 진행 사례",
      "{region} 허리디스크 비수술 후기｜다리 저림으로 시작",
      "{region} 신경외과 허리디스크 진행 사례",
    ],
    keywords: ["허리디스크", "{region}허리디스크", "신경외과디스크", "MRI"],
    compareWith: "신경성형술",
  },
  {
    id: "neuro_stenosis",
    industry: "neuro",
    name: "척추관협착증",
    cat: "척추·디스크",
    emoji: "🔻",
    titlePatterns: [
      "{region} 척추관협착증 신경외과 후기｜다리 저림으로 시작",
      "{region} 협착증 비수술 후기｜MRI 진행 사례",
      "{region} 신경외과 협착증 진행 사례",
    ],
    keywords: ["척추관협착증", "{region}협착증", "신경성파행", "신경외과협착증"],
    compareWith: "경막외신경성형술",
  },
  {
    id: "neuro_neckdisc",
    industry: "neuro",
    name: "목디스크",
    cat: "척추·디스크",
    emoji: "🦴",
    titlePatterns: [
      "{region} 목디스크 신경외과 후기｜손 저림으로 시작",
      "{region} 목디스크 비수술 후기｜MRI 진행 사례",
      "{region} 신경외과 목디스크 진행 사례",
    ],
    keywords: ["목디스크", "{region}목디스크", "경추디스크", "신경외과"],
    compareWith: "신경차단술",
  },
  {
    id: "neuro_compfx",
    industry: "neuro",
    name: "척추압박골절",
    cat: "척추·디스크",
    emoji: "🦴",
    titlePatterns: [
      "{region} 척추압박골절 신경외과 후기｜낙상 후 진행 사례",
      "{region} 압박골절 척추성형술 후기",
      "{region} 신경외과 압박골절 진행 사례",
    ],
    keywords: ["척추압박골절", "{region}압박골절", "척추성형술", "골다공증"],
    compareWith: "척추성형술",
  },

  // ─── 두통·신경통 ─── (neuro 전용)
  {
    id: "neuro_headache",
    industry: "neuro",
    name: "만성두통",
    cat: "두통·신경통",
    emoji: "🧠",
    titlePatterns: [
      "{region} 만성두통 신경외과 후기｜진통제 한계로 시작",
      "{region} 만성두통 진료 사례｜MRI 검사 진행",
      "{region} 신경외과 두통 진행 사례",
    ],
    keywords: ["만성두통", "{region}만성두통", "신경외과두통"],
    compareWith: "약물 치료",
  },
  {
    id: "neuro_migraine",
    industry: "neuro",
    name: "편두통",
    cat: "두통·신경통",
    emoji: "💢",
    titlePatterns: [
      "{region} 편두통 신경외과 후기｜발작 빈도 관리",
      "{region} 편두통 진료 사례｜약물 한계 후 시작",
      "{region} 신경외과 편두통 진행 사례",
    ],
    keywords: ["편두통", "{region}편두통", "신경외과편두통"],
    compareWith: "약물 치료",
  },
  {
    id: "neuro_trigeminal",
    industry: "neuro",
    name: "삼차신경통",
    cat: "두통·신경통",
    emoji: "⚡",
    titlePatterns: [
      "{region} 삼차신경통 신경외과 후기｜얼굴 통증으로 시작",
      "{region} 삼차신경통 진료 사례｜약물 한계 후 진행",
      "{region} 신경외과 삼차신경통 진행 사례",
    ],
    keywords: ["삼차신경통", "{region}삼차신경통", "안면통증"],
    compareWith: "약물 치료",
  },
  {
    id: "neuro_occipital",
    industry: "neuro",
    name: "후두신경통",
    cat: "두통·신경통",
    emoji: "🎯",
    titlePatterns: [
      "{region} 후두신경통 신경외과 후기｜뒷머리 통증으로 시작",
      "{region} 후두신경통 진료 사례",
      "{region} 신경외과 후두신경통 진행 사례",
    ],
    keywords: ["후두신경통", "{region}후두신경통", "뒷머리통증"],
    compareWith: "신경차단술",
  },
  {
    id: "neuro_cluster",
    industry: "neuro",
    name: "군발성두통",
    cat: "두통·신경통",
    emoji: "🌀",
    titlePatterns: [
      "{region} 군발성두통 신경외과 후기｜정해진 시간 발작",
      "{region} 군발성두통 진료 사례",
      "{region} 신경외과 군발성두통 진행 사례",
    ],
    keywords: ["군발성두통", "{region}군발성두통"],
    compareWith: "약물 치료",
  },

  // ─── 신경차단·통증 ─── (pain과 분리: neuro = 신경뿌리 차단)
  {
    id: "neuro_block",
    industry: "neuro",
    name: "신경차단술",
    cat: "신경차단·통증",
    emoji: "🎯",
    titlePatterns: [
      "{region} 신경차단술 신경외과 후기｜약물 한계 후 진행",
      "{region} 신경차단술 진료 사례｜MRI 후 진행",
      "{region} 신경외과 신경차단술 진행 사례",
    ],
    keywords: ["신경차단술", "{region}신경차단술", "신경외과시술"],
    compareWith: "신경성형술",
  },
  {
    id: "neuro_neuroplasty",
    industry: "neuro",
    name: "경막외신경성형술",
    cat: "신경차단·통증",
    emoji: "⚡",
    titlePatterns: [
      "{region} 경막외신경성형술 후기｜신경차단 후 진행",
      "{region} 신경성형술 진료 사례｜PEN 시술",
      "{region} 신경외과 신경성형술 진행 사례",
    ],
    keywords: ["경막외신경성형술", "PEN시술", "{region}신경성형술"],
    compareWith: "신경차단술",
  },
  {
    id: "neuro_rfa",
    industry: "neuro",
    name: "고주파신경치료",
    cat: "신경차단·통증",
    emoji: "🔥",
    titlePatterns: [
      "{region} 고주파신경치료 후기｜만성 통증으로 시작",
      "{region} 고주파 신경치료 진료 사례",
      "{region} 신경외과 고주파 진행 사례",
    ],
    keywords: ["고주파신경치료", "{region}고주파", "RFA"],
    compareWith: "신경차단술",
  },
  {
    id: "neuro_fims",
    industry: "neuro",
    name: "FIMS시술",
    cat: "신경차단·통증",
    emoji: "📍",
    titlePatterns: [
      "{region} FIMS시술 후기｜만성 압통으로 시작",
      "{region} FIMS 진료 사례｜근막 유착 박리",
      "{region} 신경외과 FIMS 진행 사례",
    ],
    keywords: ["FIMS시술", "{region}FIMS", "근막유착박리"],
    compareWith: "체외충격파",
  },
  {
    id: "neuro_eswt",
    industry: "neuro",
    name: "체외충격파",
    cat: "신경차단·통증",
    emoji: "💥",
    titlePatterns: [
      "{region} 체외충격파 신경외과 후기｜만성 통증으로 시작",
      "{region} 체외충격파 진료 사례｜신경외과 진행",
      "{region} 신경외과 체외충격파 진행 사례",
    ],
    keywords: ["체외충격파", "{region}체외충격파", "ESWT"],
    compareWith: "FIMS시술",
  },

  // ─── 말초신경·손저림 ─── (neuro 강세)
  {
    id: "neuro_carpal",
    industry: "neuro",
    name: "수근관증후군",
    cat: "말초신경·손저림",
    emoji: "✋",
    titlePatterns: [
      "{region} 수근관증후군 신경외과 후기｜야간 손저림으로 시작",
      "{region} 수근관증후군 진료 사례｜신경전도검사 진행",
      "{region} 신경외과 수근관 진행 사례",
    ],
    keywords: ["수근관증후군", "{region}수근관증후군", "손저림"],
    compareWith: "수술적 치료",
  },
  {
    id: "neuro_ulnar",
    industry: "neuro",
    name: "척골신경포착증후군",
    cat: "말초신경·손저림",
    emoji: "🦵",
    titlePatterns: [
      "{region} 척골신경포착증후군 후기｜새끼손가락 저림",
      "{region} 척골신경포착증후군 진료 사례",
      "{region} 신경외과 척골신경 진행 사례",
    ],
    keywords: ["척골신경포착증후군", "{region}척골신경", "팔꿈치저림"],
    compareWith: "수술적 치료",
  },
  {
    id: "neuro_peripheral",
    industry: "neuro",
    name: "말초신경병증",
    cat: "말초신경·손저림",
    emoji: "🌐",
    titlePatterns: [
      "{region} 말초신경병증 신경외과 후기｜손발 저림으로 시작",
      "{region} 말초신경병증 진료 사례",
      "{region} 신경외과 말초신경 진행 사례",
    ],
    keywords: ["말초신경병증", "{region}말초신경병증", "손발저림"],
    compareWith: "약물 치료",
  },

  // ─── 어지럼·뇌신경 ─── (neuro 전용)
  {
    id: "neuro_dizzy",
    industry: "neuro",
    name: "어지럼증",
    cat: "어지럼·뇌신경",
    emoji: "🌀",
    titlePatterns: [
      "{region} 어지럼증 신경외과 후기｜아침 기상시 발생",
      "{region} 어지럼증 진료 사례｜MRI 검사 진행",
      "{region} 신경외과 어지럼증 진행 사례",
    ],
    keywords: ["어지럼증", "{region}어지럼증", "신경외과어지럼"],
    compareWith: "이비인후과 검사",
  },
  {
    id: "neuro_brainmri",
    industry: "neuro",
    name: "뇌MRI",
    cat: "어지럼·뇌신경",
    emoji: "🧠",
    titlePatterns: [
      "{region} 뇌MRI 신경외과 후기｜두통·가족력으로 진행",
      "{region} 뇌MRI 검사 사례｜원인 감별",
      "{region} 신경외과 뇌MRI 진행 사례",
    ],
    keywords: ["뇌MRI", "{region}뇌MRI", "뇌혈관검사"],
    compareWith: "뇌CT",
  },
  {
    id: "neuro_facialspasm",
    industry: "neuro",
    name: "안면경련",
    cat: "어지럼·뇌신경",
    emoji: "👁️",
    titlePatterns: [
      "{region} 안면경련 신경외과 후기｜한쪽 떨림으로 시작",
      "{region} 안면경련 진료 사례",
      "{region} 신경외과 안면경련 진행 사례",
    ],
    keywords: ["안면경련", "{region}안면경련", "얼굴떨림"],
    compareWith: "보툴리눔 치료",
  },
  {
    id: "neuro_tinnitus",
    industry: "neuro",
    name: "이명",
    cat: "어지럼·뇌신경",
    emoji: "👂",
    titlePatterns: [
      "{region} 이명 신경외과 후기｜수면 어려움으로 시작",
      "{region} 이명 진료 사례｜원인 검사 진행",
      "{region} 신경외과 이명 진행 사례",
    ],
    keywords: ["이명", "{region}이명", "신경외과이명"],
    compareWith: "이비인후과 검사",
  },
  {
    id: "neuro_memory",
    industry: "neuro",
    name: "기억력저하",
    cat: "어지럼·뇌신경",
    emoji: "🧩",
    titlePatterns: [
      "{region} 기억력저하 신경외과 후기｜인지검사 진행",
      "{region} 기억력 진료 사례｜원인 검사",
      "{region} 신경외과 기억력저하 진행 사례",
    ],
    keywords: ["기억력저하", "{region}기억력저하", "인지기능검사"],
    compareWith: "정신건강의학과",
  },
  {
    id: "neuro_fbss",
    industry: "neuro",
    name: "척추수술후증후군",
    cat: "척추·디스크",
    emoji: "🔄",
    titlePatterns: [
      "{region} 척추수술후증후군 후기｜수술 후 통증 지속",
      "{region} FBSS 진료 사례｜신경 유착 박리",
      "{region} 신경외과 수술후증후군 진행 사례",
    ],
    keywords: ["척추수술후증후군", "FBSS", "{region}수술후증후군"],
    compareWith: "재수술",
  },
  {
    id: "neuro_sciatica",
    industry: "neuro",
    name: "좌골신경통",
    cat: "척추·디스크",
    emoji: "🦵",
    titlePatterns: [
      "{region} 좌골신경통 신경외과 후기｜다리 저림으로 시작",
      "{region} 좌골신경통 진료 사례",
      "{region} 신경외과 좌골신경통 진행 사례",
    ],
    keywords: ["좌골신경통", "{region}좌골신경통", "신경외과좌골"],
    compareWith: "신경차단술",
  },
];
