// ╔══════════════════════════════════════════════════════════╗
// ║ 🔒 FREEZE — 통증의학과 V2 · 2026-07-09                     ║
// ║ 조사(Josa) 축 종료 후 FREEZE 확정. 엔진 4파일 자립 단위.  ║
// ║ 수정 금지: 관측(survival) 완료 전까지 로직 변경 불가.     ║
// ║ 다음 축(보류): pain-prompts 구조축 / pain-data 정교화 /   ║
// ║              상담표현 clean — 모두 신규 세션에서 One Axis. ║
// ╚══════════════════════════════════════════════════════════╝

// lib/pain-data.js — 통증의학과 시술 데이터 v1.1 (derma v4 기반 v3 변환)

export const PAIN_META = {
  industry: "pain",
  label: "통증의학과",
  minLength: 2000,
};

export const PAIN_TREATMENTS = [
  // ─── 척추·디스크 ───
  {
    id: "lumbar_nerve_block",
    industry: "pain",
    name: "허리디스크 신경차단술",
    cat: "척추·디스크",
    emoji: "🎯",
    titlePatterns: [
      "{region} {name} 정보｜다리 저림 동반 허리 통증",
      "{region} {name} 비수술 치료 안내",
      "허리디스크 비수술 치료 {region} 정리",
    ],
    keywords: ["허리디스크신경차단술", "{region}허리디스크", "경막외주사", "디스크비수술"],
    compareWith: "디스크 수술",
  },
  {
    id: "cervical_nerve_block",
    industry: "pain",
    name: "목디스크 신경차단술",
    cat: "척추·디스크",
    emoji: "🦴",
    titlePatterns: [
      "{region} {name} 정보｜팔 저림 동반 목 통증",
      "{region} {name} 비수술 치료 안내",
      "목디스크 비수술 치료 {region} 정리",
    ],
    keywords: ["목디스크신경차단술", "{region}목디스크", "경추신경차단"],
    compareWith: "수술적 치료",
  },
  {
    id: "spinal_stenosis_pain",
    industry: "pain",
    name: "척추관협착증 시술",
    cat: "척추·디스크",
    emoji: "🔻",
    titlePatterns: [
      "{region} {name} 정보｜보행 시 다리 저림",
      "{region} {name} 비수술 치료 안내",
      "{region} {name} 치료 대상과 진행 방식",
    ],
    keywords: ["척추관협착증", "{region}협착증", "협착증비수술"],
    compareWith: "협착증 수술",
  },
  {
    id: "nerve_plasty",
    industry: "pain",
    name: "신경성형술(PEN)",
    cat: "척추·디스크",
    emoji: "⚡",
    titlePatterns: [
      "{region} {name} 정보｜신경 유착 통증",
      "{region} {name} 시술 특징과 대상",
      "{region} {name} 비수술 치료 안내",
    ],
    keywords: ["신경성형술", "PEN시술", "신경유착박리", "{region}신경성형술"],
    compareWith: "신경차단술",
  },
  {
    id: "chronic_pain",
    industry: "pain",
    name: "만성요통·만성통증 클리닉",
    cat: "척추·디스크",
    emoji: "🔥",
    titlePatterns: [
      "{region} {name} 정보｜약물로 조절 안 되는 통증",
      "{region} {name} 치료 방법 안내",
      "{region} {name} 치료 대상과 접근 방식",
    ],
    keywords: ["만성요통", "만성통증", "통증클리닉", "{region}만성통증"],
    compareWith: "약물 치료",
  },
  {
    id: "sciatica",
    industry: "pain",
    name: "좌골신경통 치료",
    cat: "척추·디스크",
    emoji: "🦵",
    titlePatterns: [
      "{region} {name} 정보｜엉덩이·다리 저림",
      "{region} {name} 원인과 치료 안내",
      "{region} {name} 비수술 치료 정보",
    ],
    keywords: ["좌골신경통", "이상근증후군", "{region}좌골신경통"],
    compareWith: "도수치료",
  },

  // ─── 관절·인대 ───
  {
    id: "prolotherapy_pain",
    industry: "pain",
    name: "프롤로 주사",
    cat: "관절·인대",
    emoji: "💉",
    titlePatterns: [
      "{region} {name} 정보｜인대·힘줄 손상 통증",
      "{region} {name} 시술 특징과 대상",
      "{region} {name} 치료 정보 안내",
    ],
    keywords: ["프롤로주사", "프롤로치료", "{region}프롤로"],
    compareWith: "PRP 주사",
  },
  {
    id: "prp_pain",
    industry: "pain",
    name: "PRP 주사",
    cat: "관절·인대",
    emoji: "🩸",
    titlePatterns: [
      "{region} {name} 정보｜만성 건염·관절 통증",
      "{region} {name} 시술 방식과 대상",
      "{region} {name} 치료 정보 안내",
    ],
    keywords: ["PRP주사", "자가혈주사", "{region}PRP"],
    compareWith: "프롤로 주사",
  },
  {
    id: "knee_injection",
    industry: "pain",
    name: "무릎 관절 주사",
    cat: "관절·인대",
    emoji: "🦵",
    titlePatterns: [
      "{region} {name} 정보｜계단 오를 때 무릎 통증",
      "{region} {name} 종류와 치료 안내",
      "{region} {name} 비수술 치료 정보",
    ],
    keywords: ["무릎관절주사", "히알루론산", "연골주사", "{region}무릎주사"],
    compareWith: "무릎 수술",
  },
  {
    id: "shoulder_injection",
    industry: "pain",
    name: "어깨 주사 치료",
    cat: "관절·인대",
    emoji: "💪",
    titlePatterns: [
      "{region} {name} 정보｜팔 들 때 어깨 통증",
      "{region} {name} 치료 방식과 대상",
      "{region} {name} 치료 정보 안내",
    ],
    keywords: ["어깨주사", "{region}어깨주사", "견봉하주사"],
    compareWith: "체외충격파",
  },
  {
    id: "frozen_shoulder",
    industry: "pain",
    name: "오십견 수압팽창술",
    cat: "관절·인대",
    emoji: "🌀",
    titlePatterns: [
      "{region} {name} 정보｜팔 올리기 어려운 어깨",
      "{region} {name} 시술 방식과 대상",
      "{region} {name} 치료 정보 안내",
    ],
    keywords: ["오십견", "수압팽창술", "유착성관절낭염", "{region}오십견"],
    compareWith: "도수치료",
  },
  {
    id: "stem_cell_knee",
    industry: "pain",
    name: "무릎 줄기세포·연골재생",
    cat: "관절·인대",
    emoji: "🧬",
    titlePatterns: [
      "{region} {name} 정보｜연골 손상 무릎 통증",
      "{region} {name} 치료 대상과 방식",
      "{region} {name} 재생치료 정보 안내",
    ],
    keywords: ["무릎줄기세포", "연골재생", "카티스템", "{region}줄기세포"],
    compareWith: "PRP 주사",
  },
  {
    id: "tmd",
    industry: "pain",
    name: "턱관절 통증치료(TMD)",
    cat: "관절·인대",
    emoji: "👄",
    titlePatterns: [
      "{region} {name} 정보｜입 벌릴 때 턱 통증",
      "{region} {name} 원인과 치료 안내",
      "{region} {name} 치료 방법 정보",
    ],
    keywords: ["턱관절치료", "TMD", "개구장애", "{region}턱관절"],
    compareWith: "구강내장치",
  },

  // ─── 재활·물리 ───
  {
    id: "manual_therapy_pain",
    industry: "pain",
    name: "도수치료",
    cat: "재활·물리",
    emoji: "👐",
    titlePatterns: [
      "{region} {name} 정보｜자세 불균형·근육 통증",
      "{region} {name} 진행 방식과 대상",
      "{region} {name} 치료 정보 안내",
    ],
    keywords: ["도수치료", "{region}도수치료", "교정치료"],
    compareWith: "물리치료",
  },
  {
    id: "shockwave_pain",
    industry: "pain",
    name: "체외충격파",
    cat: "재활·물리",
    emoji: "⚡",
    titlePatterns: [
      "{region} {name} 정보｜만성 힘줄·근막 통증",
      "{region} {name} 적용 부위와 방식",
      "{region} {name} 치료 정보 안내",
    ],
    keywords: ["체외충격파", "ESWT", "{region}체외충격파"],
    compareWith: "도수치료",
  },
  {
    id: "ims_trigger",
    industry: "pain",
    name: "근막통증 IMS 치료",
    cat: "재활·물리",
    emoji: "🎯",
    titlePatterns: [
      "{region} {name} 정보｜뭉치고 결리는 근육 통증",
      "{region} {name} 치료 방식과 대상",
      "{region} {name} 근막통증 치료 정보",
    ],
    keywords: ["IMS치료", "트리거포인트", "근막통증", "{region}IMS"],
    compareWith: "도수치료",
  },
  {
    id: "radiofrequency_ablation",
    industry: "pain",
    name: "고주파 열응고술",
    cat: "재활·물리",
    emoji: "🔥",
    titlePatterns: [
      "{region} {name} 정보｜반복되는 만성 통증",
      "{region} {name} 시술 특징과 대상",
      "{region} {name} 치료 정보 안내",
    ],
    keywords: ["고주파열응고술", "RFA", "{region}고주파"],
    compareWith: "신경차단술",
  },
  {
    id: "fibromyalgia",
    industry: "pain",
    name: "섬유근육통",
    cat: "재활·물리",
    emoji: "🌐",
    titlePatterns: [
      "{region} {name} 정보｜전신에 퍼지는 통증",
      "{region} {name} 치료 접근법 안내",
      "{region} {name} 치료 대상과 방식",
    ],
    keywords: ["섬유근육통", "전신통증", "{region}섬유근육통"],
    compareWith: "약물 치료",
  },

  // ─── 두통·신경 ───
  {
    id: "headache_nerve_block",
    industry: "pain",
    name: "두통 신경차단",
    cat: "두통·신경",
    emoji: "🧠",
    titlePatterns: [
      "{region} {name} 정보｜반복되는 만성 두통",
      "{region} {name} 치료 방식과 대상",
      "{region} {name} 비수술 치료 정보",
    ],
    keywords: ["두통신경차단", "후두신경통", "{region}두통치료"],
    compareWith: "약물 치료",
  },
  {
    id: "postherpetic_neuralgia",
    industry: "pain",
    name: "대상포진 후 신경통",
    cat: "두통·신경",
    emoji: "⚠️",
    titlePatterns: [
      "{region} {name} 정보｜대상포진 후 지속 통증",
      "{region} {name} 치료 방법 안내",
      "{region} {name} 치료 대상과 방식",
    ],
    keywords: ["대상포진후신경통", "PHN", "{region}대상포진"],
    compareWith: "약물 치료",
  },
  {
    id: "neuropathic_pain",
    industry: "pain",
    name: "신경병증성 통증",
    cat: "두통·신경",
    emoji: "💢",
    titlePatterns: [
      "{region} {name} 정보｜저림·화끈거리는 신경통",
      "{region} {name} 원인과 치료 안내",
      "{region} {name} 치료 방법 정보",
    ],
    keywords: ["신경병증성통증", "신경통", "{region}신경통"],
    compareWith: "약물 치료",
  },
  {
    id: "cancer_pain",
    industry: "pain",
    name: "암성 통증 관리",
    cat: "두통·신경",
    emoji: "🎗️",
    titlePatterns: [
      "{region} {name} 정보｜약물로 부족한 암성 통증",
      "{region} {name} 관리 단계와 방식",
      "{region} {name} 치료 정보 안내",
    ],
    keywords: ["암성통증", "암통증관리", "{region}암성통증"],
    compareWith: "약물 치료",
  },
  {
    id: "cervicogenic_pain",
    industry: "pain",
    name: "경추성 어깨·목 통증",
    cat: "두통·신경",
    emoji: "🦒",
    titlePatterns: [
      "{region} {name} 정보｜목에서 시작된 어깨 결림",
      "{region} {name} 원인과 치료 안내",
      "{region} {name} 치료 방법 정보",
    ],
    keywords: ["경추성통증", "{region}경추성통증"],
    compareWith: "도수치료",
  },

  // ─── 족부·하지 ───
  {
    id: "plantar_fasciitis_pain",
    industry: "pain",
    name: "족저근막염 치료",
    cat: "족부·하지",
    emoji: "🦶",
    titlePatterns: [
      "{region} {name} 정보｜아침 첫발 뒤꿈치 통증",
      "{region} {name} 치료 방법 안내",
      "{region} {name} 비수술 치료 정보",
    ],
    keywords: ["족저근막염", "발바닥통증", "{region}족저근막염"],
    compareWith: "체외충격파",
  },
  {
    id: "ankle_pain",
    industry: "pain",
    name: "발목 인대 손상 치료",
    cat: "족부·하지",
    emoji: "🦶",
    titlePatterns: [
      "{region} {name} 정보｜자주 삐는 발목",
      "{region} {name} 치료 방식과 대상",
      "{region} {name} 치료 정보 안내",
    ],
    keywords: ["발목인대", "발목염좌", "{region}발목치료"],
    compareWith: "물리치료",
  },
  {
    id: "wrist_elbow_pain",
    industry: "pain",
    name: "손목·팔꿈치 통증 치료",
    cat: "족부·하지",
    emoji: "✋",
    titlePatterns: [
      "{region} {name} 정보｜타이핑·테니스엘보 통증",
      "{region} {name} 원인과 치료 안내",
      "{region} {name} 치료 방법 정보",
    ],
    keywords: ["손목통증", "테니스엘보", "골프엘보", "{region}손목팔꿈치"],
    compareWith: "체외충격파",
  },
  {
    id: "coccyx_pelvic_pain",
    industry: "pain",
    name: "꼬리뼈·골반 통증 치료",
    cat: "족부·하지",
    emoji: "🪑",
    titlePatterns: [
      "{region} {name} 정보｜오래 앉기 힘든 꼬리뼈 통증",
      "{region} {name} 원인과 치료 안내",
      "{region} {name} 치료 방법 정보",
    ],
    keywords: ["꼬리뼈통증", "미골통", "골반통증", "{region}꼬리뼈"],
    compareWith: "도수치료",
  },
];