// lib/pain-data.js — 통증의학과 시술 데이터 v1.1 (derma v4 기반 v3 변환)

export const PAIN_META = {
  industry: "pain",
  label: "통증의학과",
  minLength: 2000,
};

export const PAIN_TREATMENTS = [
  // ─── 척추·디스크 ───
  {
    id: "lumbar_nerve_block",
    industry: "pain",
    name: "허리디스크 신경차단술",
    cat: "척추·디스크",
    emoji: "🎯",
    titlePatterns: [
      "{region} 허리디스크 신경차단술 후기｜수술 없이 진행한 이야기",
      "{region} 통증의학과 신경차단술 진행 사례",
      "허리디스크 비수술 치료 {region}에서 정리된 이야기",
    ],
    keywords: ["허리디스크신경차단술", "{region}허리디스크", "경막외주사", "디스크비수술"],
    compareWith: "디스크 수술",
  },
  {
    id: "cervical_nerve_block",
    industry: "pain",
    name: "목디스크 신경차단술",
    cat: "척추·디스크",
    emoji: "🦴",
    titlePatterns: [
      "{region} 목디스크 신경차단술 후기｜팔 저림으로 시작",
      "{region} 통증의학과 목디스크 비수술 진행 사례",
    ],
    keywords: ["목디스크신경차단술", "{region}목디스크", "경추신경차단"],
    compareWith: "수술적 치료",
  },
  {
    id: "spinal_stenosis_pain",
    industry: "pain",
    name: "척추관협착증 시술",
    cat: "척추·디스크",
    emoji: "🔻",
    titlePatterns: [
      "{region} 척추관협착증 시술 후기｜걷다 멈추는 증상",
      "{region} 통증의학과 협착증 비수술 진행 사례",
    ],
    keywords: ["척추관협착증", "{region}협착증", "협착증비수술"],
    compareWith: "협착증 수술",
  },
  {
    id: "nerve_plasty",
    industry: "pain",
    name: "신경성형술(PEN)",
    cat: "척추·디스크",
    emoji: "⚡",
    titlePatterns: [
      "{region} 신경성형술 후기｜PEN 시술 진행 사례",
      "{region} 통증의학과 신경유착박리 진행 기록",
    ],
    keywords: ["신경성형술", "PEN시술", "신경유착박리", "{region}신경성형술"],
    compareWith: "신경차단술",
  },
  {
    id: "chronic_pain",
    industry: "pain",
    name: "만성요통·만성통증 클리닉",
    cat: "척추·디스크",
    emoji: "🔥",
    titlePatterns: [
      "{region} 만성요통 치료 후기｜약물 한계 후 시작",
      "{region} 만성통증 클리닉 진행 사례",
    ],
    keywords: ["만성요통", "만성통증", "통증클리닉", "{region}만성통증"],
    compareWith: "약물 치료",
  },
  {
    id: "sciatica",
    industry: "pain",
    name: "좌골신경통 치료",
    cat: "척추·디스크",
    emoji: "🦵",
    titlePatterns: [
      "{region} 좌골신경통 치료 후기｜엉덩이 저림으로 시작",
      "{region} 이상근증후군 진행 사례",
    ],
    keywords: ["좌골신경통", "이상근증후군", "{region}좌골신경통"],
    compareWith: "도수치료",
  },

  // ─── 관절·인대 ───
  {
    id: "prolotherapy_pain",
    industry: "pain",
    name: "프롤로 주사",
    cat: "관절·인대",
    emoji: "💉",
    titlePatterns: [
      "{region} 프롤로 주사 후기｜인대 손상으로 시작",
      "{region} 통증의학과 프롤로 진행 사례",
    ],
    keywords: ["프롤로주사", "프롤로치료", "{region}프롤로"],
    compareWith: "PRP 주사",
  },
  {
    id: "prp_pain",
    industry: "pain",
    name: "PRP 주사",
    cat: "관절·인대",
    emoji: "🩸",
    titlePatterns: [
      "{region} PRP 주사 후기｜만성 건염으로 시작",
      "{region} 통증의학과 자가혈 주사 진행 사례",
    ],
    keywords: ["PRP주사", "자가혈주사", "{region}PRP"],
    compareWith: "프롤로 주사",
  },
  {
    id: "knee_injection",
    industry: "pain",
    name: "무릎 관절 주사",
    cat: "관절·인대",
    emoji: "🦵",
    titlePatterns: [
      "{region} 무릎 관절 주사 후기｜계단 통증으로 시작",
      "{region} 통증의학과 무릎 히알루론산 진행 사례",
    ],
    keywords: ["무릎관절주사", "히알루론산", "연골주사", "{region}무릎주사"],
    compareWith: "무릎 수술",
  },
  {
    id: "shoulder_injection",
    industry: "pain",
    name: "어깨 주사 치료",
    cat: "관절·인대",
    emoji: "💪",
    titlePatterns: [
      "{region} 어깨 주사 치료 후기｜팔 들 때 통증",
      "{region} 통증의학과 어깨 진행 사례",
    ],
    keywords: ["어깨주사", "{region}어깨주사", "견봉하주사"],
    compareWith: "체외충격파",
  },
  {
    id: "frozen_shoulder",
    industry: "pain",
    name: "오십견 수압팽창술",
    cat: "관절·인대",
    emoji: "🌀",
    titlePatterns: [
      "{region} 오십견 수압팽창술 후기｜팔이 올라간 이야기",
      "{region} 통증의학과 오십견 진행 사례",
    ],
    keywords: ["오십견", "수압팽창술", "유착성관절낭염", "{region}오십견"],
    compareWith: "도수치료",
  },
  {
    id: "stem_cell_knee",
    industry: "pain",
    name: "무릎 줄기세포·연골재생",
    cat: "관절·인대",
    emoji: "🧬",
    titlePatterns: [
      "{region} 무릎 줄기세포 후기｜연골 재생 진행 사례",
      "{region} 통증의학과 카티스템 진행 기록",
    ],
    keywords: ["무릎줄기세포", "연골재생", "카티스템", "{region}줄기세포"],
    compareWith: "PRP 주사",
  },
  {
    id: "tmd",
    industry: "pain",
    name: "턱관절 통증치료(TMD)",
    cat: "관절·인대",
    emoji: "👄",
    titlePatterns: [
      "{region} 턱관절 통증 치료 후기｜개구장애로 시작",
      "{region} 통증의학과 TMD 진행 사례",
    ],
    keywords: ["턱관절치료", "TMD", "개구장애", "{region}턱관절"],
    compareWith: "구강내장치",
  },

  // ─── 재활·물리 ───
  {
    id: "manual_therapy_pain",
    industry: "pain",
    name: "도수치료",
    cat: "재활·물리",
    emoji: "👐",
    titlePatterns: [
      "{region} 도수치료 후기｜자세 교정 위해 시작",
      "{region} 통증의학과 도수치료 진행 사례",
    ],
    keywords: ["도수치료", "{region}도수치료", "교정치료"],
    compareWith: "물리치료",
  },
  {
    id: "shockwave_pain",
    industry: "pain",
    name: "체외충격파",
    cat: "재활·물리",
    emoji: "⚡",
    titlePatterns: [
      "{region} 체외충격파 후기｜만성 염증으로 시작",
      "{region} 통증의학과 체외충격파 진행 사례",
    ],
    keywords: ["체외충격파", "ESWT", "{region}체외충격파"],
    compareWith: "도수치료",
  },
  {
    id: "ims_trigger",
    industry: "pain",
    name: "근막통증 IMS 치료",
    cat: "재활·물리",
    emoji: "🎯",
    titlePatterns: [
      "{region} IMS 치료 후기｜만성 결림으로 시작",
      "{region} 통증의학과 트리거포인트 진행 사례",
    ],
    keywords: ["IMS치료", "트리거포인트", "근막통증", "{region}IMS"],
    compareWith: "도수치료",
  },
  {
    id: "radiofrequency_ablation",
    industry: "pain",
    name: "고주파 열응고술",
    cat: "재활·물리",
    emoji: "🔥",
    titlePatterns: [
      "{region} 고주파 열응고술 후기｜만성 통증으로 시작",
      "{region} 통증의학과 고주파 진행 사례",
    ],
    keywords: ["고주파열응고술", "RFA", "{region}고주파"],
    compareWith: "신경차단술",
  },
  {
    id: "fibromyalgia",
    industry: "pain",
    name: "섬유근육통",
    cat: "재활·물리",
    emoji: "🌐",
    titlePatterns: [
      "{region} 섬유근육통 치료 후기｜전신통증으로 시작",
      "{region} 통증의학과 섬유근육통 진행 사례",
    ],
    keywords: ["섬유근육통", "전신통증", "{region}섬유근육통"],
    compareWith: "약물 치료",
  },

  // ─── 두통·신경 ───
  {
    id: "headache_nerve_block",
    industry: "pain",
    name: "두통 신경차단",
    cat: "두통·신경",
    emoji: "🧠",
    titlePatterns: [
      "{region} 두통 신경차단 후기｜만성 두통으로 시작",
      "{region} 통증의학과 후두신경 진행 사례",
    ],
    keywords: ["두통신경차단", "후두신경통", "{region}두통치료"],
    compareWith: "약물 치료",
  },
  {
    id: "postherpetic_neuralgia",
    industry: "pain",
    name: "대상포진 후 신경통",
    cat: "두통·신경",
    emoji: "⚠️",
    titlePatterns: [
      "{region} 대상포진 후 신경통 후기｜통증 지속으로 시작",
      "{region} 통증의학과 신경통 진행 사례",
    ],
    keywords: ["대상포진후신경통", "PHN", "{region}대상포진"],
    compareWith: "약물 치료",
  },
  {
    id: "neuropathic_pain",
    industry: "pain",
    name: "신경병증성 통증",
    cat: "두통·신경",
    emoji: "💢",
    titlePatterns: [
      "{region} 신경병증성 통증 치료 후기｜만성 신경통",
      "{region} 통증의학과 신경병증 진행 사례",
    ],
    keywords: ["신경병증성통증", "신경통", "{region}신경통"],
    compareWith: "약물 치료",
  },
  {
    id: "cancer_pain",
    industry: "pain",
    name: "암성 통증 관리",
    cat: "두통·신경",
    emoji: "🎗️",
    titlePatterns: [
      "{region} 암성 통증 관리 후기｜약물 한계 후 시작",
      "{region} 통증의학과 암성 통증 진행 사례",
    ],
    keywords: ["암성통증", "암통증관리", "{region}암성통증"],
    compareWith: "약물 치료",
  },
  {
    id: "cervicogenic_pain",
    industry: "pain",
    name: "경추성 어깨·목 통증",
    cat: "두통·신경",
    emoji: "🦒",
    titlePatterns: [
      "{region} 경추성 어깨·목 통증 후기｜만성 결림으로 시작",
      "{region} 통증의학과 경추성 진행 사례",
    ],
    keywords: ["경추성통증", "{region}경추성통증"],
    compareWith: "도수치료",
  },

  // ─── 족부·하지 ───
  {
    id: "plantar_fasciitis_pain",
    industry: "pain",
    name: "족저근막염 치료",
    cat: "족부·하지",
    emoji: "🦶",
    titlePatterns: [
      "{region} 족저근막염 치료 후기｜아침 첫 발 통증",
      "{region} 통증의학과 족저근막염 진행 사례",
    ],
    keywords: ["족저근막염", "발바닥통증", "{region}족저근막염"],
    compareWith: "체외충격파",
  },
  {
    id: "ankle_pain",
    industry: "pain",
    name: "발목 인대 손상 치료",
    cat: "족부·하지",
    emoji: "🦶",
    titlePatterns: [
      "{region} 발목 인대 손상 치료 후기｜자주 삐는 발목",
      "{region} 통증의학과 발목 진행 사례",
    ],
    keywords: ["발목인대", "발목염좌", "{region}발목치료"],
    compareWith: "물리치료",
  },
  {
    id: "wrist_elbow_pain",
    industry: "pain",
    name: "손목·팔꿈치 통증 치료",
    cat: "족부·하지",
    emoji: "✋",
    titlePatterns: [
      "{region} 손목·팔꿈치 통증 치료 후기｜타이핑·테니스엘보",
      "{region} 통증의학과 손목·팔꿈치 진행 사례",
    ],
    keywords: ["손목통증", "테니스엘보", "골프엘보", "{region}손목팔꿈치"],
    compareWith: "체외충격파",
  },
  {
    id: "coccyx_pelvic_pain",
    industry: "pain",
    name: "꼬리뼈·골반 통증 치료",
    cat: "족부·하지",
    emoji: "🪑",
    titlePatterns: [
      "{region} 꼬리뼈 통증 치료 후기｜앉기 어려움으로 시작",
      "{region} 통증의학과 미골 진행 사례",
    ],
    keywords: ["꼬리뼈통증", "미골통", "골반통증", "{region}꼬리뼈"],
    compareWith: "도수치료",
  },
];